server:
  port: 8080

spring:
  application:
    name: sesac.dev.sell
  datasource:
    url: jdbc:mysql://localhost:3306/schoolmatedb?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  thymeleaf:
    cache: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/**/*.xml