spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_MYSQL_USERNAME}
    password: ${SPRING_MYSQL_PASSWORD}

  session:
    redis:
      repository-type: indexed
      flush-mode: on_save

  data:
    redis:  
      host: ${SPRING_REDIS_HOST}
      password: ${SPRING_REDIS_PASSWORD}
      port: ${SPRING_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  server:
    address: 0.0.0.0
    port: 80
    
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
