spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/sesac?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${SPRING_MYSQL_USERNAME}
    password: ${SPRING_MYSQL_PASSWORD}

  session:
    redis:
      repository-type: indexed
      flush-mode: on_save
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      password: ${SPRING_REDIS_PASSWORD}
      port: ${SPRING_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
