spring:
  datasource:
    url: ${SPRING_MYSQL_HOST}
    username: ${SPRING_MYSQL_USERNAME}
    password: ${SPRING_MYSQL_PASSWORD}

  session:
    redis:
      repository-type: indexed
      flush-mode: on_save
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      password: ${SPRING_REDIS_PASSWORD}
      port: ${SPRING_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
