name: Trigger CodePipeline on Push to Main

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때 트리거

jobs:
  trigger:
    runs-on: ubuntu-22.04  
    steps:
      - name: AWS CLI 설치
        run: |
          sudo apt-get install awscli

      - name: AWS CLI 설정
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
      - name: CodePipeline 실행
        run: |
          aws codepipeline start-pipeline-execution --name cicid-pipeloine
